package:
  name: realtime
  version: 0.1.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base

pipeline:
  - name: build it
    runs: |
      cp -r packages /etc/packages

